# url: http://zeitkraut.at
# baseurl: /sxsw

# url: http://localhost
# port: 4000
# baseurl: /sxsw

gems:
  - jekyll-redirect-from
  
# Site settings
title: IT Kraut @ SXSW
email: ze@itkraut.at
description: "Austin Hippie event meets Germany’s finest engineers. We are a community of German geeks promoting German Engineering in tech. We build international brigdes between startups, established Fortune 500 companies."
author: Jan Kus
copyright: IT Kraut
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: f0c30d
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Ralph Christoph
  pic: 1
  position: Advisor
  social:
    - title: twitter
      url: https://twitter.com/ralphchristoph
    - title: facebook
      url: https://www.facebook.com/ralph.christoph
    - title: linkedin
      url: http://de.linkedin.com/in/ralphchristoph
- name: Johannes Heck
  pic: 2
  position: German Engineer
  social:
    - title: twitter
      url: https://twitter.com/yoyostile
    - title: facebook
      url: https://www.facebook.com/ralph.christoph
    - title: linkedin
      url: http://de.linkedin.com/in/ralphchristoph

- name: Florian Krakau
  pic: 3
  position: Head of Media
  social:
    - title: twitter
      url: https://twitter.com/dotdean
    - title: facebook
      url: https://www.facebook.com/dotdean
    - title: linkedin
      url: https://de.linkedin.com/in/floriankrakau

- name: Jan Kus
  pic: 4
  position: Wholesaler
  social:
    - title: twitter
      url: http://twitter.com/koos
    - title: facebook
      url: http://facebook.com/jbvkoos
    - title: linkedin
      url: de.linkedin.com/in/jbvkoos

- name: Tobias Schiwek
  pic: 5
  position: Wholesaler
  social:
    - title: twitter
      url: https://twitter.com/tobiasschiwek
    - title: facebook
      url: https://www.facebook.com/schiwek
    - title: linkedin
      url: https://de.linkedin.com/in/schiwek
# - name: Isa Slowik
#   pic: 6
#   position: Compositor
- name: Vidar Andersen
  pic: 7
  position: Vidar Andersen Consulting
  social:
    - title: twitter
      url: https://twitter.com/blacktar
    - title: facebook
      url: https://www.facebook.com/Blacktar
    - title: linkedin
      url: https://de.linkedin.com/in/vidarandersen

  # social:
  #   - title: facebook
  #     url: https://www.facebook.com/schiwek
  #   - title: linkedin
  #     url: https://de.linkedin.com/in/schiwek

# Team names, titles and social links
delegation:
- name: Parker Thompson
  pic: 8
  position: Partner at 500 Startups
  social:
    - title: twitter
      url: https://twitter.com/pt
    - title: facebook
      url: https://www.facebook.com/m.parker.thompson
    - title: linkedin
      url: https://www.linkedin.com/in/parkert
# - name: Sebastian Doerfel
#   pic: 9
#   position: Co-Founder & COO at adsquare GmbH
#   social:
#     - title: twitter
#       url: https://twitter.com/astrosurfing
#     - title: facebook
#       url: https://www.facebook.com/sebastian.doerfel
#     - title: linkedin
#       url: https://www.linkedin.com/pub/sebastian-doerfel/6/29b/650
- name: Dr. Nazim Cetin
  pic: 10
  position: Vice President at Bertelsmann
  social:
    - title: linkedin
      url: https://www.linkedin.com/pub/nazim-cetin/57/2a5/b60
# - name: Vidar Andersen
#   pic: 7
#   position: Vidar Andersen Consulting
#   social:
#     - title: twitter
#       url: https://twitter.com/blacktar
#     - title: facebook
#       url: https://www.facebook.com/Blacktar
#     - title: linkedin
#       url: https://de.linkedin.com/in/vidarandersen
- name: Ralph Christoph
  pic: 1
  position: cologne on pop GmbH
  social:
    - title: twitter
      url: https://twitter.com/ralphchristoph
    - title: facebook
      url: https://www.facebook.com/ralph.christoph
    - title: linkedin
      url: http://de.linkedin.com/in/ralphchristoph

# - name: Florian Krakau
#   pic: 3
#   position: Daily Coffee Break
#   social:
#     - title: twitter
#       url: https://twitter.com/dotdean
#     - title: facebook
#       url: https://www.facebook.com/dotdean
#     - title: linkedin
#       url: https://de.linkedin.com/in/floriankrakau

- name: Jan Kus
  pic: 4
  position: CEO Railslove GmbH & hack.institute
  social:
    - title: twitter
      url: http://twitter.com/koos
    - title: facebook
      url: http://facebook.com/jbvkoos
    - title: linkedin
      url: de.linkedin.com/in/jbvkoos
- name: Tobias Schiwek
  pic: 5
  position: ‎Bertelsmann Entrepreneurs Program at Bertelsmann
  social:
    - title: twitter
      url: https://twitter.com/tobiasschiwek
    - title: facebook
      url: https://www.facebook.com/schiwek
    - title: linkedin
      url: https://de.linkedin.com/in/schiwek
# - name: Tim Schumacher
#   pic: 12
#   position: Internet Founder, Entrepreneur and Investor
#   social:
#     - title: twitter
#       url: https://twitter.com/timschu
#     - title: facebook
#       url: https://www.facebook.com/TimSchumacher
#     - title: linkedin
#       url: https://www.linkedin.com/in/timschumacher
# - name: Dan Taylor
#   pic: 11
#   position: Photographer at Heisenberg Media
#   social:
#     - title: twitter
#       url: https://twitter.com/mountaindan
#     - title: facebook
#       url: https://www.facebook.com/dantaylor1
#     - title: linkedin
#       url: http://at.linkedin.com/in/mountaindan

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/ZeITKraut
  - title: facebook
    url: https://www.facebook.com/pages/ITKraut/318870264971897

# Postal address (add as many lines as necessary)
address:
  - line: Germany
  - line: Euope

# Build settings
markdown: kramdown
permalink: pretty
